### ISSUE TITLE
最后两篇文章的布局出错

### ISSUE THREAD

**Issue by kun775** [haocity/typecho-newcity#2]
最后两篇文章的布局比正常的要宽一些，不知道是不是我个人问题
[截图](http://kun775.oss-cn-shenzhen.aliyuncs.com/tmp/2017/08/3028958938.jpg)
只要拉到最后一页，就会出现问题，刷新一下就正常了

-------------
删除那两篇文章就正常了

**Comment by haocity** [comment]
.............好奇怪的问题。。
